### ISSUE TITLE
Promise-based loader

### ISSUE THREAD

**Issue by normanrz** [normanrz/emscripten-constraints#11]
The loader should have a Promise-based interface:

1. Promises are the now the defacto standard for async code in JS
2. We can easily do memoization

**Comment by philippotto** [comment]
We need a promise implementation for this, don't we? I would suggest a [ES6 Promise polyfill](https://github.com/jakearchibald/es6-promise)

**Comment by normanrz** [comment]
Maybe we dont need a polyfill: http://caniuse.com/#feat=promises

**Comment by philippotto** [comment]
Perfect :+1:

**Comment by philippotto** [comment]
Fixed by 907f0ab.
