### ISSUE TITLE
Benchmark solvers

### ISSUE THREAD

**Issue by normanrz** [normanrz/emscripten-constraints#6]
Reference: http://lively-kernel.org/babelsberg/users/timfelgentreff/ecoop_artifact.html

* Run benchmarks in mocha on travis
* Load tests into lively or extract tests from lively to compare?

**Comment by fniephaus** [comment]
Port from Tim's bench and add more benchmarks

**Comment by normanrz** [comment]
Please include a comparision of the filesizes

**Comment by fniephaus** [comment]
Sure! :)
